### PR TITLE
Add support for GetLogs

### PR DESCRIPTION
**Pull request by alexellis**
## Description

Add support for GetLogs

## How has this been tested

Tested end to end with OpenFaaS Standard, and with a new unit test.

Closes: #24 #21

### CODE REVIEW

**Comment by nitishkumar71** [comment]
Thank You @alexellis for taking a look at it. So simple fix but yet somehow I could not figure it out.

**Comment by alexellis** [comment]
No worries, we looked at it on the community call together and got it working eventually.

@welteki and @kevin-lindsay-1

**Comment by alexellis** [comment]
@nitishkumar71 do you want to work on some more code examples for getting/listing functions and namespaces and secrets, perhaps in an examples folder?

`get_example.go`
`list_example.go`
`secrets_example.go`

etc?

**Comment by nitishkumar71** [comment]
Sure, I will add the relevant examples.

**Pull request merged**
