### PR TITLE
Set openfaas=1 on namespaces for create and update

### LINKED ISSUE #15: set openfaas annotation for namespace create/update operation
add `openfaas=1` annotation to create and update namespace operation

### PR DESCRIPTION
**Pull request by nitishkumar71**
## Description

Add `openfaas` annotation for create/update namespace operation in `go-sdk`

## Motivation and Context

- [x] I have raised an issue to propose this change **this is required**
Closes #15 
## How Has This Been Tested?

1. Created a test code script which need to be tested on pro version. `faasd` does not support annotations, so we need to do test on `faas-netes` pro version.
```
package main

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"net/url"
	"os"

	"github.com/openfaas/faas-provider/types"
	"github.com/openfaas/go-sdk"
)

func main() {
	username := os.Getenv("OPENFAAS_USERNAME")
	password := os.Getenv("OPENFAAS_PASSWORD")

	gatewayURL, _ := url.Parse(os.Getenv("OPENFAAS_GATEWAY_URL"))
	auth := &sdk.BasicAuth{
		Username: username,
		Password: password,
	}
	nsName := "test-sdk-ns"

	client := sdk.NewClient(gatewayURL, auth, http.DefaultClient)

	// create namespace
	_, err := client.CreateNamespace(context.Background(), types.FunctionNamespace{
		Name: nsName,
		Labels: map[string]string{
			"purpose": "test",
		},
	})

	if err != nil {
		log.Fatalf("Namespace creation Failed: %s", err)
	}
	fmt.Printf("Namespace %s created!\n", nsName)

	// get namespace
	res, err := client.GetNamespace(context.Background(), nsName)

	if err != nil {
		log.Fatalf("Namespace get Failed: %s", err)
	}

	fmt.Printf("GetNamespace: %q\n", res)

	// update namespace
	_, err = client.UpdateNamespace(context.Background(), types.FunctionNamespace{
		Name: nsName,
		Labels: map[string]string{
			"purpose": "test",
			"demo":    "false",
		},
	})

	if err != nil {
		log.Fatalf("Namespace update Failed: %s", err)
	}

	res, err = client.GetNamespace(context.Background(), nsName)

	if err != nil {
		log.Fatalf("Namespace get Failed: %s", err)
	}

	demo, found := res.Labels["demo"]

	if !found || demo != "false" {
		log.Fatalf("Namespace update Failed: %s", err)
	}
	fmt.Printf("Updated Namespace: %q\n", res)

	// delete namespace
	err = client.DeleteNamespace(context.Background(), nsName)

	if err != nil {
		log.Fatalf("Namespace %s delete Failed: %s", nsName, err)
	}
	fmt.Printf("Namespace %s deleted!\n", nsName)

	// get namespaces
	namespaces, err := client.GetNamespaces(context.Background())
	fmt.Printf("Namespaces: %q\n", namespaces)
}

```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Commits:

- [x] My commit message has a body and describe how this was tested and why it is required.
- [x] I have signed-off my commits with `git commit -s` for the Developer Certificate of Origin (DCO)

Code:

- [x] My code follows the code style of this project.
- [ ] I have added tests to cover my changes.

Docs:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by alexellis** [comment]
I am fine with this. @welteki ?

**Comment by welteki** [comment]
Looks good. I'm fine with this as well.

**Comment by alexellis** [comment]
Thanks @nitishkumar71

**Comment by alexellis** [comment]
For vendor back to faas-cli - https://github.com/openfaas/go-sdk/releases/tag/v0.2.7

**Pull request merged**
