### PR TITLE
Add examples for all go sdk operations

### LINKED ISSUE #26: Add examples for all supported functionalities
Examples should be added for all the supported functionalities by `go-sdk`, so users can use it to build capabilities at their end.

### PR DESCRIPTION
**Pull request by nitishkumar71**
## Description

Add examples for all go sdk operations

## Motivation and Context

- [x] I have raised an issue to propose this change **this is required**
Closes #26
## How Has This Been Tested?

All examples have been copied from the previous PRs test cases.
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Commits:

- [x] My commit message has a body and describe how this was tested and why it is required.
- [x] I have signed-off my commits with `git commit -s` for the Developer Certificate of Origin (DCO)

Code:

- [x] My code follows the code style of this project.
- [x] I have added tests to cover my changes.

Docs:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by alexellis** [comment]
Hi @nitishkumar71 .. I'm wondering how people can run these examples? And how can we maintain them over time?

Can you add a README file?

Perhaps we can take inspiration from github-go, and create a folder for each example with a main.go?

https://github.com/google/go-github/tree/master/example

**Comment by nitishkumar71** [comment]
> Hi @nitishkumar71 .. I'm wondering how people can run these examples? And how can we maintain them over time?
> 
> Can you add a README file?
> 
> Perhaps we can take inspiration from github-go, and create a folder for each example with a main.go?
> 
> https://github.com/google/go-github/tree/master/example

Sounds good to me.

I will do it.

**Comment by alexellis** [comment]
I like the new structure, just a suggestion:

```
	fns, err := client.GetFunctions(context.Background(), "openfaas-fn")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Get Failed: %s\n", err)
		os.Exit(1)
	}
```

vs

```
	fns, err := client.GetFunctions(context.Background(), "openfaas-fn")
	if err != nil {
		log.Printf("Get Failed: %s", err)
	}
```

This ran further code when I didn't have a valid gateway, instead of exiting.

and fmt vs log

**Comment by nitishkumar71** [comment]
> I like the new structure, just a suggestion:
> 
> ```
> 	fns, err := client.GetFunctions(context.Background(), "openfaas-fn")
> 	if err != nil {
> 		fmt.Fprintf(os.Stderr, "Get Failed: %s\n", err)
> 		os.Exit(1)
> 	}
> ```
> 
> vs
> 
> ```
> 	fns, err := client.GetFunctions(context.Background(), "openfaas-fn")
> 	if err != nil {
> 		log.Printf("Get Failed: %s", err)
> 	}
> ```
> 
> This ran further code when I didn't have a valid gateway, instead of exiting.
> 
> and fmt vs log

feedback changes are done.

**Review by alexellis — APPROVED** [review]
Approved

**Pull request merged**
